CS349 WatGUI: A2UnitTests.cpp File Reference
A2UnitTests.cpp File Reference
#include "gtest/gtest.h"
#include "XApplication.h"
#include "XWindow.h"
#include "MainPanel.h"
#include "Button.h"
#include "Slider.h"
#include "TurtleGraphics.h"
Classes
class ListenerCounter
Functions
TEST (A2UnitTest, XApplicationCreateDestroy)
TEST (A2UnitTest, XApplicationRunOnceTest)
void FlushEventQueue (XApplication *app)
void SimulateClick (XApplication *app, XWindow *win, Point where)
void SimulateDrag (XApplication *app, XWindow *win, Point start, Point middle, Point end)
TEST (A2UnitTest, ButtonTests)
TEST (A2UnitTest, SliderTests)
TEST (A2UnitTest, TurtleTests)
Function Documentation
void FlushEventQueue (XApplication * app)
Definition at line 80 of file A2UnitTests.cpp.
References cs349::XApplication::GetEventQueue(), cs349::EventQueue::GetNumEventsInQueue(), and cs349::XApplication::Run().
Referenced by TEST().
{
   const int MAX_ATTEMPTS_TO_CLEAR_QUEUE = 100;
   for (int i = 0; i < MAX_ATTEMPTS_TO_CLEAR_QUEUE; i++) {
     app->Run(true);
     if (app->GetEventQueue()->GetNumEventsInQueue() < 1) {
       break;
     }
   }
 }
void SimulateClick (XApplication * app, XWindow * win, Point where)
Definition at line 91 of file A2UnitTests.cpp.
References cs349::EventQueue::AddEventToQueue(), cs349::XApplication::GetEventQueue(), cs349::MouseEvent::mouseDown, and cs349::MouseEvent::mouseUp.
Referenced by TEST().
{
   app->GetEventQueue()->AddEventToQueue(new MouseEvent(win, MouseEvent::mouseDown, where));
   app->GetEventQueue()->AddEventToQueue(new MouseEvent(win, MouseEvent::mouseUp, where));
 }
void SimulateDrag (XApplication * app, XWindow * win, Point start, Point middle, Point end)
Definition at line 97 of file A2UnitTests.cpp.
References cs349::EventQueue::AddEventToQueue(), cs349::XApplication::GetEventQueue(), cs349::MouseEvent::mouseDown, cs349::MouseEvent::mouseDrag, and cs349::MouseEvent::mouseUp.
Referenced by TEST().
{
   app->GetEventQueue()->AddEventToQueue(new MouseEvent(win, MouseEvent::mouseDown, start));
   app->GetEventQueue()->AddEventToQueue(new MouseEvent(win, MouseEvent::mouseDrag, middle));
   app->GetEventQueue()->AddEventToQueue(new MouseEvent(win, MouseEvent::mouseUp, end));
 }
TEST (A2UnitTest , XApplicationCreateDestroy)
Definition at line 13 of file A2UnitTests.cpp.
References cs349::EventQueue::AddEventToQueue(), cs349::XApplication::GetEventQueue(), cs349::XApplication::GetInstance(), cs349::EventQueue::GetNumEventsInQueue(), and cs349::XWindow::GetWindowList().
{
   // Delete any app that is already lying around
   XApplication* app = XApplication::GetInstance();
   delete app;
   // Get new instance
   app = XApplication::GetInstance();
   EXPECT_EQ(0UL, XWindow::GetWindowList().size());
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   // Create a window and add an event to the event queue
   XWindow* win = new XWindow("Dummy", Rectangle(0, 0, 100, 100));
   EXPECT_EQ(1UL, XWindow::GetWindowList().size());
   app->GetEventQueue()->AddEventToQueue(new PaintEvent(win, Rectangle()));
   EXPECT_LT(0, app->GetEventQueue()->GetNumEventsInQueue());
   delete app;
   EXPECT_EQ(0UL, XWindow::GetWindowList().size());
   // Get a new instance, verify it's a new instance by checking that
   // the event queue is empty
   app = XApplication::GetInstance();
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
 }
TEST (A2UnitTest , XApplicationRunOnceTest)
Definition at line 38 of file A2UnitTests.cpp.
References cs349::EventQueue::AddEventToQueue(), cs349::XApplication::GetEventQueue(), cs349::XApplication::GetInstance(), cs349::EventQueue::GetNumEventsInQueue(), cs349::XWindow::GetWindowList(), and cs349::XApplication::Run().
{
   // Delete any app that is already lying around
   XApplication* app = XApplication::GetInstance();
   delete app;
   // Get new instance
   app = XApplication::GetInstance();
   EXPECT_EQ(0UL, XWindow::GetWindowList().size());
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   // Create a window and add an event to the event queue
   XWindow* win = new XWindow("Dummy", Rectangle(0, 0, 100, 100));
   app->GetEventQueue()->AddEventToQueue(new PaintEvent(win, Rectangle()));
   int numEvents = app->GetEventQueue()->GetNumEventsInQueue();
   // Run one iteration of the event loop
   app->Run(true);
   EXPECT_EQ(numEvents-1, app->GetEventQueue()->GetNumEventsInQueue());
 }
TEST (A2UnitTest , ButtonTests)
Definition at line 103 of file A2UnitTests.cpp.
References cs349::Button::AddActionListener(), cs349::Component::AddComponent(), FlushEventQueue(), cs349::XApplication::GetEventQueue(), cs349::XApplication::GetInstance(), cs349::EventQueue::GetNumEventsInQueue(), ListenerCounter::lastComponentName, ListenerCounter::numActionsPerformed, cs349::Component::SetBounds(), cs349::XWindow::SetVisible(), cs349::Component::SetVisible(), SimulateClick(), and SimulateDrag().
{
   // Delete any app that is already lying around
   XApplication* app = XApplication::GetInstance();
   delete app;
   // Get new instance
   app = XApplication::GetInstance();
   const int buttonSize = 100;
   XWindow* win = new XWindow("Dummy", Rectangle(0, 0, 2*buttonSize, buttonSize));
   Button* leftButton = new Button("LEFT", "Left");
   Button* rightButton = new Button("RIGHT", "Right");
   leftButton->SetBounds(Rectangle(0, 0, buttonSize, buttonSize));
   rightButton->SetBounds(Rectangle(buttonSize, 0, buttonSize, buttonSize));
   Point leftButtonCenter(buttonSize/2, buttonSize/2);
   Point rightButtonCenter(buttonSize + buttonSize/2, buttonSize/2);
   win->AddComponent(leftButton);
   win->AddComponent(rightButton);
   ListenerCounter counter;
   leftButton->AddActionListener(&counter);
   rightButton->AddActionListener(&counter);
   // Set the window to visible so it responds to clicks
   win->SetVisible(true);
   // Buttons that are not visible should not respond to clicks...
   leftButton->SetVisible(false);
   rightButton->SetVisible(false);
   // Flush the repaints
   FlushEventQueue(app);
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   EXPECT_EQ(0, counter.numActionsPerformed);
   EXPECT_EQ(string(""), counter.lastComponentName);
   SimulateClick(app, win, leftButtonCenter);
   SimulateClick(app, win, rightButtonCenter);
   EXPECT_EQ(4, app->GetEventQueue()->GetNumEventsInQueue());
   FlushEventQueue(app);
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   EXPECT_EQ(0, counter.numActionsPerformed);
   EXPECT_EQ(string(""), counter.lastComponentName);
   // Now test with visible buttons...
   leftButton->SetVisible(true);
   rightButton->SetVisible(true);
   // Flush the repaints
   FlushEventQueue(app);
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   SimulateClick(app, win, leftButtonCenter);
   EXPECT_EQ(2, app->GetEventQueue()->GetNumEventsInQueue());
   FlushEventQueue(app);
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   EXPECT_EQ(1, counter.numActionsPerformed);
   EXPECT_EQ(string("LEFT"), counter.lastComponentName);
   SimulateClick(app, win, rightButtonCenter);
   EXPECT_EQ(2, app->GetEventQueue()->GetNumEventsInQueue());
   FlushEventQueue(app);
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   EXPECT_EQ(2, counter.numActionsPerformed);
   EXPECT_EQ(string("RIGHT"), counter.lastComponentName);
   // Test mouse down then out then in
   SimulateDrag(app, win, leftButtonCenter, rightButtonCenter, leftButtonCenter);
   EXPECT_EQ(3, app->GetEventQueue()->GetNumEventsInQueue());
   FlushEventQueue(app);
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   EXPECT_EQ(3, counter.numActionsPerformed);
   EXPECT_EQ(string("LEFT"), counter.lastComponentName);
   // Test mouse down then out with button up on the outside
   SimulateDrag(app, win, leftButtonCenter, rightButtonCenter, rightButtonCenter);
   EXPECT_EQ(3, app->GetEventQueue()->GetNumEventsInQueue());
   FlushEventQueue(app);
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   EXPECT_EQ(3, counter.numActionsPerformed);
   EXPECT_EQ(string("LEFT"), counter.lastComponentName);
 }
TEST (A2UnitTest , SliderTests)
Definition at line 203 of file A2UnitTests.cpp.
References cs349::Component::AddComponent(), cs349::Slider::AddValueListener(), FlushEventQueue(), cs349::Slider::GetCurValue(), cs349::XApplication::GetEventQueue(), cs349::XApplication::GetInstance(), cs349::Slider::GetMaximum(), cs349::Slider::GetMinimum(), cs349::EventQueue::GetNumEventsInQueue(), cs349::Slider::HORIZONTAL_SLIDER, ListenerCounter::lastComponentName, ListenerCounter::numValuesChanged, cs349::Component::SetBounds(), cs349::Slider::SetCurValue(), cs349::Slider::SetMaximum(), cs349::Slider::SetMinimum(), cs349::XWindow::SetVisible(), cs349::Component::SetVisible(), and SimulateClick().
{
   // Delete any app that is already lying around
   XApplication* app = XApplication::GetInstance();
   delete app;
   // Get new instance
   app = XApplication::GetInstance();
   const int sliderSize = 100;
   XWindow* win = new XWindow("Dummy", Rectangle(0, 0, 2*sliderSize, sliderSize));
   Slider* slider = new Slider("SLIDER", Slider::HORIZONTAL_SLIDER);
   slider->SetBounds(Rectangle(0, 0, sliderSize, sliderSize));
   Point sliderLeft(0, sliderSize/2);
   Point sliderRight(sliderSize-1, sliderSize/2); // Set right side to
                                                  // be one less than
                                                  // the bounds to be
                                                  // considered "in"
                                                  // the slider
   Point sliderCenter(sliderSize/2, sliderSize/2);
   win->AddComponent(slider);
   // Some basic tests before testing interaction
   slider->SetMinimum(0);
   slider->SetMaximum(100);
   slider->SetCurValue(0);
   EXPECT_EQ(0, slider->GetMinimum());
   EXPECT_EQ(100, slider->GetMaximum());
   EXPECT_EQ(0, slider->GetCurValue());
   slider->SetCurValue(97);
   EXPECT_EQ(97, slider->GetCurValue());
   slider->SetCurValue(-1);
   EXPECT_EQ(0, slider->GetCurValue());
   slider->SetCurValue(101);
   EXPECT_EQ(100, slider->GetCurValue());
   slider->SetCurValue(0);
   // Now test interaction
   ListenerCounter counter;
   slider->AddValueListener(&counter);
   EXPECT_EQ(0, counter.numValuesChanged);
   EXPECT_EQ(string(""), counter.lastComponentName);
   // Set the window to visible so it responds to clicks
   win->SetVisible(true);
   // Sliders that are not visible should not respond to clicks...
   slider->SetVisible(false);
   // Flush the repaints
   FlushEventQueue(app);
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   EXPECT_EQ(0, counter.numValuesChanged);
   EXPECT_EQ(string(""), counter.lastComponentName);
   SimulateClick(app, win, sliderCenter);
   EXPECT_EQ(2, app->GetEventQueue()->GetNumEventsInQueue());
   FlushEventQueue(app);
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   EXPECT_EQ(0, counter.numValuesChanged);
   EXPECT_EQ(string(""), counter.lastComponentName);
   EXPECT_EQ(0, slider->GetCurValue());
   // Now test with visible slider...
   slider->SetVisible(true);
   // Flush the repaints
   FlushEventQueue(app);
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   EXPECT_EQ(0, slider->GetCurValue());
   SimulateClick(app, win, sliderCenter);
   EXPECT_EQ(2, app->GetEventQueue()->GetNumEventsInQueue());
   FlushEventQueue(app);
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   EXPECT_EQ(1, counter.numValuesChanged);
   EXPECT_EQ(string("SLIDER"), counter.lastComponentName);
   EXPECT_EQ(50, slider->GetCurValue());
   SimulateClick(app, win, sliderLeft);
   EXPECT_EQ(2, app->GetEventQueue()->GetNumEventsInQueue());
   FlushEventQueue(app);
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   EXPECT_EQ(2, counter.numValuesChanged);
   EXPECT_EQ(string("SLIDER"), counter.lastComponentName);
   EXPECT_EQ(0, slider->GetCurValue());
   SimulateClick(app, win, sliderRight);
   EXPECT_EQ(2, app->GetEventQueue()->GetNumEventsInQueue());
   FlushEventQueue(app);
   EXPECT_EQ(0, app->GetEventQueue()->GetNumEventsInQueue());
   EXPECT_EQ(3, counter.numValuesChanged);
   EXPECT_EQ(string("SLIDER"), counter.lastComponentName);
   EXPECT_EQ(100, slider->GetCurValue());
 }
TEST (A2UnitTest , TurtleTests)
Definition at line 323 of file A2UnitTests.cpp.
References cs349::TurtleGraphics::AddValueListener(), cs349::TurtleGraphics::BroadcastInstructionsChanged(), ListenerCounter::lastComponentName, and ListenerCounter::numValuesChanged.
{
   TurtleGraphics* turtle = new TurtleGraphics("TURTLE");
   ListenerCounter counter;
   turtle->AddValueListener(&counter);
   EXPECT_EQ(0, counter.numValuesChanged);
   EXPECT_EQ(string(""), counter.lastComponentName);
   turtle->BroadcastInstructionsChanged();
   EXPECT_EQ(1, counter.numValuesChanged);
   EXPECT_EQ(string("TURTLE"), counter.lastComponentName);
 }