CS349 WatGUI: cs349::EventQueue Class Reference
cs349::EventQueue Class Reference
#include "EventQueue.h"
Public Member Functions
virtual ~EventQueue ()
virtual void AddEventToQueue (Event *e)
virtual void ClearEventQueue ()
virtual void ProcessNextEvent ()
virtual int GetNumEventsInQueue () const
virtual int GetNumTimers () const
virtual queue< Event * > GetEvents () const
Private Member Functions
void AddTimer (Timer *timer)
void RemoveTimer (Timer *timer)
Private Attributes
queue< Event * > eventQueue
vector< Timer * > timers
Friends
class Timer
Detailed Description
The EventQueue serves as the central message hub within an interactive application: All messages intended for any part of the interactive application should be packaged up as an Event and placed on the application's EventQueue.
Examples of events are those generated by pointer devices (e.g., a mouse), a keyboard, or the base window system instructing the application that it needs to repaint itself. The EventQueue and Event classes provide a standardized way to queue up and deliver all of these different types of events.
EventQueue maintains a queue of all the events that have been received by the application. This is a first-in-first-out (FIFO) queue, so events are processed in the order they are received.
When an event is taken off of the event queue, DispatchEvent() is called, indicating the Event should be delivered and procesed.
X events are added to the EventQueue object via the XApplication object.
EventQueue also maintains a list of timers that it regularly "services" so they can check whether they need to tell their listeners that a certain amount of time has elapsed. This allows the application to regularly update itself (e.g., for animations) without using threads. (Single-threaded interactive applications are significantly easier to code.)
Important note: Normally, the rule of thumb with memory management is that if you allocate something, you are responsible for deallocating it. As an exception to this rule, when adding events to EventQueue, EventQueue will take care of deleting the event after it has been delivered/processed.
Definition at line 56 of file EventQueue.h.
Constructor & Destructor Documentation
cs349::EventQueue::~EventQueue () virtual
When destructor is called, frees up any memory (Events) held in the queue.
Definition at line 9 of file EventQueue.cpp.
{
     // Clear up any memory laying around
     this->ClearEventQueue();
   }
Member Function Documentation
void cs349::EventQueue::AddEventToQueue (Event * e) virtual
Adds an event to the queue. The EventQueue object will delete the memory pointed to by the event after it has been dispatched (or if the EventQueue object is destroyed).
Definition at line 25 of file EventQueue.cpp.
Referenced by cs349::XApplication::CheckForXEvents(), cs349::XWindow::Repaint(), cs349::scheme_simulate_key_event(), cs349::scheme_simulate_mouse_event(), cs349::scheme_simulate_paint_event(), cs349::Timer::ServiceTimer(), SimulateClick(), SimulateDrag(), and TEST().
{
     this->eventQueue.push(e);
   }
void cs349::EventQueue::AddTimer (Timer * timer) private
Add a Timer for regular execution in the event loop.
Definition at line 14 of file EventQueue.cpp.
Referenced by cs349::Timer::Start().
{
     timers.push_back(timer);
   }
void cs349::EventQueue::ClearEventQueue () virtual
Clears the event queue of all pending events. Its only real purpose is to support unit testing.
Definition at line 29 of file EventQueue.cpp.
{
     while (this->eventQueue.size() > 0) {
       Event* e = eventQueue.front();
       eventQueue.pop();
       delete(e);
     }
   }
queue< Event * > cs349::EventQueue::GetEvents () const virtual
Returns all the events in the queue. Only needed for debugging and unit test purposes
Definition at line 89 of file EventQueue.cpp.
{
     return eventQueue;
   }
int cs349::EventQueue::GetNumEventsInQueue () const virtual
Returns the number of events currently queued up.
Important: Even if there are no events in the EventQueue, you should call ProcessNextEvent() regularly so that timers are properly serviced. However, you should not repeatedly call ProcessNextEvent() if there are no events present, without sleeping a little bit. If you don't sleep for a bit, the CPU will be throttled unnecessarily, the TAs will become slightly irritated, and marks will be deducted.
Definition at line 81 of file EventQueue.cpp.
Referenced by FlushEventQueue(), and TEST().
{
     return (int)this->eventQueue.size();
   }
int cs349::EventQueue::GetNumTimers () const virtual
Returns the number of timers being managed by EventQueue.
Definition at line 85 of file EventQueue.cpp.
Referenced by TEST().
{
     return (int)this->timers.size();
   }
void cs349::EventQueue::ProcessNextEvent () virtual
This method performs a single run of event processing. It services the timers, then removes the next event from the event queue, calls its DispatchEvent() method, and frees memory for the event.
Definition at line 37 of file EventQueue.cpp.
References cs349::Event::DispatchEvent(), LOG_TODO, and cs349::Timer::ServiceTimer().
Referenced by cs349::XApplication::Run(), and TEST().
{
     /*
      * This is one of the more important parts of an interactive
      * application. In this method, you need to:
      * - Service the timers to them a chance to operate.
      *   (already coded this for you, below)
      * - You should then take/remove an event off of the event queue and
      *   dispatch it using the DispatchEvent()
      * - Once done, the Event's memory should be deallocated
      */
     /*
      * Give timers a chance to operate.
      * Important: Since timers can remove themselves from the
      * EventQueue, we need to create a separate list when iterating
      * through the timers, since the contents of the list may change
      * as a result of a timer removing itself from the list.
      */
     vector<Timer*> localList = this->timers;
     for (vector<Timer*>::iterator iter=localList.begin(); iter != localList.end(); iter++) {
       Timer* timer = (*iter);
       // TODO (Mike): Technically, this should not be necessary.
       // However, there have been some issues where NULL pointers get
       // on the list due to some issue involving malloc, that we
       // haven't been able to track down.
       if (timer) {
         timer->ServiceTimer();
       }
     }
     LOG_TODO << "TODO CS349: Implement EventQueue logic in ProcessNextEvent()";
     // As described above: take event from head of queue, dispatch it,
     // then free its memory)
 // TODO CS349
       if(this->eventQueue.size()>0){
           Event* event = this->eventQueue.front();
           this->eventQueue.pop();
           event->DispatchEvent();
           delete event;
       }
       else;//do nothing
   }
void cs349::EventQueue::RemoveTimer (Timer * timer) private
Remove timer from regular execution in event loop.
Definition at line 18 of file EventQueue.cpp.
Referenced by cs349::Timer::Stop(), and cs349::Timer::~Timer().
{
     // Remove a timer from our queue. And yes, it *is* ridiculous that
     // it takes this much to remove items from vectors in C++
     vector<Timer*>::iterator where = remove(this->timers.begin(), this->timers.end(), timer);
     this->timers.erase(where, this->timers.end());
   }
Friends And Related Function Documentation
friend class Timer friend
Definition at line 61 of file EventQueue.h.
Member Data Documentation
queue<Event*> cs349::EventQueue::eventQueue private
Definition at line 58 of file EventQueue.h.
vector<Timer*> cs349::EventQueue::timers private
Definition at line 59 of file EventQueue.h.
The documentation for this class was generated from the following files:
EventQueue.h
EventQueue.cpp