CS349 WatGUI: cs349::TurtleGraphicsForwardOp Class Reference
cs349::TurtleGraphicsForwardOp Class Reference
#include "TurtleGraphicsOp.h"
Public Member Functions
TurtleGraphicsForwardOp (double amount, bool penDown)
virtual AffineTransform GetNewTransform (long stepNum) const
virtual long GetNumSteps () const
virtual void ExecuteOp (Graphics *g, long stepNum) const
virtual string ToString () const
virtual string AsSexp () const
Public Member Functions inherited from cs349::TurtleGraphicsOp
virtual ~TurtleGraphicsOp ()
Private Member Functions
double GetDistance (long stepNum) const
Private Attributes
double amount
long numSteps
bool penDown
Detailed Description
Definition at line 20 of file TurtleGraphicsOp.h.
Constructor & Destructor Documentation
cs349::TurtleGraphicsForwardOp::TurtleGraphicsForwardOp (double amount, bool penDown)
Definition at line 6 of file TurtleGraphicsOp.cpp.
References amount, numSteps, and penDown.
{
     this->amount   = amount;
     this->penDown  = penDown;
     this->numSteps = max(1L, (long) ((amount >= 0L) ? amount : -amount));
   }
Member Function Documentation
string cs349::TurtleGraphicsForwardOp::AsSexp () const virtual
Implements cs349::TurtleGraphicsOp.
Definition at line 41 of file TurtleGraphicsOp.cpp.
References amount, and penDown.
{
     stringstream sstream;
     sstream << "(turtle-forward " << this->amount << " " << ((this->penDown) ? "#t" : "#f") << ")";
     return sstream.str();
   }
void cs349::TurtleGraphicsForwardOp::ExecuteOp (Graphics * g, long stepNum) const virtual
Implements cs349::TurtleGraphicsOp.
Definition at line 27 of file TurtleGraphicsOp.cpp.
References cs349::Graphics::DrawLine(), GetDistance(), cs349::Graphics::GetTransform(), LOG_DEBUG, and penDown.
{
     if (penDown) {
       double distance = GetDistance(stepNum);
       LOG_DEBUG << "Forward Op, drawing line from (" << (g->GetTransform() * Point(0,0)).x << ", " << (g->GetTransform() * Point(0,0)).y << ") to (" << (g->GetTransform() * Point(distance, 0)).x << ", " << (g->GetTransform() * Point(distance, 0)).y << ")";
       g->DrawLine(Point(0,0), Point(distance, 0));
     }
   }
double cs349::TurtleGraphicsForwardOp::GetDistance (long stepNum) const private
Definition at line 12 of file TurtleGraphicsOp.cpp.
References amount, and numSteps.
Referenced by ExecuteOp(), and GetNewTransform().
{
     double t = max(0L, min(stepNum, numSteps));
     t /= numSteps;
     return t * amount;
   }
AffineTransform cs349::TurtleGraphicsForwardOp::GetNewTransform (long stepNum) const virtual
Implements cs349::TurtleGraphicsOp.
Definition at line 18 of file TurtleGraphicsOp.cpp.
References GetDistance(), and cs349::AffineTransform::MakeTranslation().
{
     double distance = GetDistance(stepNum);
     return AffineTransform::MakeTranslation(distance, 0.0);
   }
long cs349::TurtleGraphicsForwardOp::GetNumSteps () const virtual
Implements cs349::TurtleGraphicsOp.
Definition at line 23 of file TurtleGraphicsOp.cpp.
References numSteps.
{
     return numSteps;
   }
string cs349::TurtleGraphicsForwardOp::ToString () const virtual
Implements cs349::TurtleGraphicsOp.
Definition at line 35 of file TurtleGraphicsOp.cpp.
References amount, numSteps, and penDown.
{
     stringstream sstream;
     sstream << "Turtle Forward Op (amount: " << this->amount << ", penDown: " << this->penDown << " numSteps: " << this->numSteps << ")";
     return sstream.str();
   }
Member Data Documentation
double cs349::TurtleGraphicsForwardOp::amount private
Definition at line 22 of file TurtleGraphicsOp.h.
Referenced by AsSexp(), GetDistance(), ToString(), and TurtleGraphicsForwardOp().
long cs349::TurtleGraphicsForwardOp::numSteps private
Definition at line 23 of file TurtleGraphicsOp.h.
Referenced by GetDistance(), GetNumSteps(), ToString(), and TurtleGraphicsForwardOp().
bool cs349::TurtleGraphicsForwardOp::penDown private
Definition at line 24 of file TurtleGraphicsOp.h.
Referenced by AsSexp(), ExecuteOp(), ToString(), and TurtleGraphicsForwardOp().
The documentation for this class was generated from the following files:
TurtleGraphicsOp.h
TurtleGraphicsOp.cpp