CS349 WatGUI: cs349::TurtleGraphics Class Reference
cs349::TurtleGraphics Class Reference
#include "TurtleGraphics.h"
Public Member Functions
TurtleGraphics (const string &name)
virtual ~TurtleGraphics ()
void Rotate (double theta, bool redrawNow=true)
void RotateInDegrees (double degrees, bool redrawNow=true)
void Forward (double amount, bool penDown, bool redrawNow=true)
void DrawText (const string &text, bool redrawNow=true)
void DrawPoint (bool redrawNow=true)
vector< const TurtleGraphicsOp * > GetInstructions () const
void ClearInstructions ()
long GetNumSteps () const
void GoToStep (long stepNum)
void BroadcastInstructionsChanged ()
void AddValueListener (ValueListener *l)
void RemoveValueListener (ValueListener *l)
double GetOrientation (long stepNum) const
Point GetPosition (long stepNum) const
AffineTransform GetAffineTransform (long stepNum) const
Public Member Functions inherited from cs349::SchemeComponent
SchemeComponent (const string &name)
void ClearInstructions ()
vector< string > GetInstructions () const
virtual bool HandleKeyEvent (const KeyEvent &e)
virtual bool HandleMouseEvent (const MouseEvent &e)
Public Member Functions inherited from cs349::Component
Component (const string &name)
virtual ~Component ()
virtual string GetName () const
virtual void AddComponent (Component *child)
virtual void RemoveComponent (Component *child)
virtual unsigned long GetBackgroundColor () const
virtual Rectangle GetBounds () const
virtual unsigned long GetForegroundColor () const
virtual Component * GetParent ()
virtual XWindow * GetParentWindow ()
virtual bool IsPointInComponent (const Point &p) const
virtual bool IsVisible () const
virtual void Paint (Graphics *g)
virtual void Repaint ()
virtual void Repaint (const Rectangle &r)
virtual void SetBackgroundColor (unsigned long c)
virtual void SetForegroundColor (unsigned long c)
virtual void SetBounds (const Rectangle &r)
virtual void SetLocation (const Point &p)
virtual void SetDebugDelay (unsigned long delayMS)
virtual void SetParent (Component *parent)
virtual void SetSize (int width, int height)
virtual void SetVisible (bool visible)
long GetComponentNum () const
vector< Component * > GetDepthFirstInteractorTree () const
vector< Component * > GetBreadthFirstInteractorTree () const
Protected Member Functions
virtual void PaintComponent (Graphics *graphics)
Private Member Functions
void DeleteInstructions ()
AffineTransform WalkInstructions (Graphics *g, long stepNum, bool executeOps) const
void NotifyListeners ()
Static Private Member Functions
static double GetRotation (const AffineTransform &t)
Private Attributes
vector< TurtleGraphicsOp * > instructions
long drawStepNum
vector< ValueListener * > listeners
Static Private Attributes
static const int TURTLE_LENGTH = 10
Additional Inherited Members
Static Public Member Functions inherited from cs349::Component
static Component * GetComponent (long componentNum)
Protected Attributes inherited from cs349::Component
vector< Component * > children
All the children of this Component.
Detailed Description
A Component that supports drawing via turtle graphics instructions. The instructions to control the turtle can be manipulated via C++ code or within Scheme.
For the purposes of creating an application that can play back turtle instructions, the methods you will be most interested in are the GetNumSteps() method (which indicates how many steps the turtle can execute from start to finish, for all the instructions it currently has stored), and GoToStep(), which will cause the TurtleGraphics display to display that particular step.
Note that there are no facilities to animate drawing: You must create a Timer object to animate the TurtleGraphics playback.
Definition at line 30 of file TurtleGraphics.h.
Constructor & Destructor Documentation
cs349::TurtleGraphics::TurtleGraphics (const string & name)
Constructs a TurtleGraphics object with the specified name (used for identification purposes for unit tests).
Definition at line 11 of file TurtleGraphics.cpp.
References drawStepNum.
     : SchemeComponent(name)
   {
     this->drawStepNum = 0;
   }
cs349::TurtleGraphics::~TurtleGraphics () virtual
Definition at line 17 of file TurtleGraphics.cpp.
References DeleteInstructions().
{
     DeleteInstructions();
   }
Member Function Documentation
void cs349::TurtleGraphics::AddValueListener (ValueListener * l)
Adds a listener to this component, which will be called when the turtle's instructions have changed. This component is not responsible for the memory management of the ValueListener – external code is responsible for removing the listener and deleting it when it is no longer needed.
Definition at line 201 of file TurtleGraphics.cpp.
References listeners.
Referenced by TEST().
{
     listeners.push_back(l);
   }
void cs349::TurtleGraphics::BroadcastInstructionsChanged ()
Called by scripts to indicate that the instructions have been changed, so controls and other dependent code can update itself
Definition at line 191 of file TurtleGraphics.cpp.
References NotifyListeners().
Referenced by cs349::marshall_turtle_call(), and TEST().
{
     this->NotifyListeners();
   }
void cs349::TurtleGraphics::ClearInstructions ()
Clears all instructions for the turtle.
Definition at line 28 of file TurtleGraphics.cpp.
References DeleteInstructions(), and cs349::Component::Repaint().
Referenced by cs349::marshall_turtle_call().
{
     DeleteInstructions();
     this->Repaint();
   }
void cs349::TurtleGraphics::DeleteInstructions () private
Definition at line 21 of file TurtleGraphics.cpp.
References instructions.
Referenced by ClearInstructions(), and ~TurtleGraphics().
{
     for (vector<TurtleGraphicsOp*>::iterator i = instructions.begin(); i != instructions.end(); i++) {
       delete *i;
     }
     instructions.erase(instructions.begin(), instructions.end());
   }
void cs349::TurtleGraphics::DrawPoint (bool redrawNow = true)
Draws a point at the current location of the turtle, optionally redrawing it now or sometime in the future (the delay is useful if giving a bunch of commands at once).
Definition at line 78 of file TurtleGraphics.cpp.
References GetNumSteps(), GoToStep(), and instructions.
Referenced by cs349::scheme_turtle_draw_point().
{
     instructions.push_back(new TurtleGraphicsDrawPointOp());
     if (redrawNow) {
       this->GoToStep(this->GetNumSteps());
     }
   }
void cs349::TurtleGraphics::DrawText (const string & text, bool redrawNow = true)
Draws text at the current location of the turtle, optionally redrawing it now or sometime in the future (the delay is useful if giving a bunch of commands at once).
Definition at line 71 of file TurtleGraphics.cpp.
References GetNumSteps(), GoToStep(), and instructions.
Referenced by cs349::scheme_turtle_draw_text().
{
     instructions.push_back(new TurtleGraphicsDrawTextOp(text));
     if (redrawNow) {
       this->GoToStep(this->GetNumSteps());
     }
   }
void cs349::TurtleGraphics::Forward (double amount, bool penDown, bool redrawNow = true)
Moves the turtle forward by the amount specified, optionally redrawing it now or sometime in the future (the delay is useful if giving a bunch of commands at once).
Definition at line 64 of file TurtleGraphics.cpp.
References GetNumSteps(), GoToStep(), and instructions.
Referenced by cs349::TurtlePanel::PaintComponent(), and cs349::scheme_turtle_forward().
{
     instructions.push_back(new TurtleGraphicsForwardOp(amount, penDown));
     if (redrawNow) {
       this->GoToStep(this->GetNumSteps());
     }
   }
AffineTransform cs349::TurtleGraphics::GetAffineTransform (long stepNum) const
Returns the affine transform used by the turtle at the step specified. You won't need this.
Definition at line 49 of file TurtleGraphics.cpp.
References WalkInstructions().
Referenced by GetOrientation(), GetPosition(), and cs349::scheme_turtle_get_affine_transform().
{
     return this->WalkInstructions(NULL, stepNum, false);
   }
vector< const TurtleGraphicsOp * > cs349::TurtleGraphics::GetInstructions () const
Retrieves the list of turtle instructions. Used for the Scheme interpreter.
Definition at line 33 of file TurtleGraphics.cpp.
References instructions.
Referenced by cs349::scheme_turtle_get_instructions().
{
     vector<const TurtleGraphicsOp*> return_instructions;
     for (vector<TurtleGraphicsOp*>::const_iterator i = instructions.begin(); i != instructions.end(); i++) {
       return_instructions.push_back(*i);
     }
     return return_instructions;
   }
long cs349::TurtleGraphics::GetNumSteps () const
Returns the number of steps the turtle can take to execute all of its instructions.
Definition at line 41 of file TurtleGraphics.cpp.
References instructions.
Referenced by DrawPoint(), DrawText(), Forward(), cs349::marshall_turtle_call(), Rotate(), and WalkInstructions().
{
     long numSteps = 0;
     for (vector<TurtleGraphicsOp*>::const_iterator i = instructions.begin(); i != instructions.end(); i++) {
       numSteps += (*i)->GetNumSteps();
     }
     return numSteps;
   }
double cs349::TurtleGraphics::GetOrientation (long stepNum) const
Returns the current orientation of the turtle. Used for scripts.
Definition at line 100 of file TurtleGraphics.cpp.
References GetAffineTransform(), and GetRotation().
Referenced by cs349::scheme_turtle_get_orientation().
{
     AffineTransform t = this->GetAffineTransform(stepNum);
     return GetRotation(t);
   }
Point cs349::TurtleGraphics::GetPosition (long stepNum) const
Returns the current position of the turtle. Used for scripts.
Definition at line 105 of file TurtleGraphics.cpp.
References GetAffineTransform(), and LOG_TODO.
Referenced by cs349::scheme_turtle_get_position().
{
     LOG_TODO << "TODO CS349: Implement GetPosition";
     AffineTransform t = this->GetAffineTransform(stepNum);
     Point origin;
     return t * origin;
   }
double cs349::TurtleGraphics::GetRotation (const AffineTransform & t) static private
Definition at line 85 of file TurtleGraphics.cpp.
References PI, cs349::Point::x, and cs349::Point::y.
Referenced by GetOrientation(), and WalkInstructions().
{
     Point origin;
     Point unitX = Point(1, 0);
     Point newOrigin = t * origin;
     Point newUnitX = t * unitX;
     double new_x = newUnitX.x - newOrigin.x;
     double new_y = newUnitX.y - newOrigin.y;
     double vector_cos = new_x / sqrt(new_x * new_x + new_y * new_y);
     double theta = acos(vector_cos);
     if (new_y < 0) {
       theta = 2*PI - theta;
     }
     return theta;
   }
void cs349::TurtleGraphics::GoToStep (long stepNum)
Requests the TurtleGraphics Component to cue up to, and draw the step number specified.
Definition at line 112 of file TurtleGraphics.cpp.
References drawStepNum, and cs349::Component::Repaint().
Referenced by DrawPoint(), DrawText(), Forward(), Rotate(), and cs349::scheme_turtle_go_to_step().
{
     this->drawStepNum = stepNum;
     this->Repaint();
   }
void cs349::TurtleGraphics::NotifyListeners () private
Definition at line 195 of file TurtleGraphics.cpp.
References listeners.
Referenced by BroadcastInstructionsChanged().
{
     for (vector<ValueListener*>::iterator i = listeners.begin(); i != listeners.end(); i++) {
       (*i)->ValueChanged(this);
     }
   }
void cs349::TurtleGraphics::PaintComponent (Graphics * g) protected virtual
The method that does the actual painting of the component once the Graphics context object has been set up by the Paint method.
The method is pure virtual because it should be overridden by subclasses to do the actual painting.
Reimplemented from cs349::SchemeComponent.
Definition at line 184 of file TurtleGraphics.cpp.
References drawStepNum, cs349::Graphics::GetTransform(), cs349::SchemeComponent::PaintComponent(), cs349::Graphics::SetTransform(), and WalkInstructions().
{
     AffineTransform originalTransform = graphics->GetTransform();
     SchemeComponent::PaintComponent(graphics);
     graphics->SetTransform(originalTransform);
     this->WalkInstructions(graphics, drawStepNum, true);
   }
void cs349::TurtleGraphics::RemoveValueListener (ValueListener * l)
Removes the specified ValueListener from the TurtleGraphics.
Definition at line 205 of file TurtleGraphics.cpp.
References listeners.
{
     remove(listeners.begin(), listeners.end(), l);
   }
void cs349::TurtleGraphics::Rotate (double theta, bool redrawNow = true)
Rotates the turtle by the amount specified, optionally redrawing it now or sometime in the future (the delay is useful if giving a bunch of commands at once).
Definition at line 53 of file TurtleGraphics.cpp.
References GetNumSteps(), GoToStep(), and instructions.
Referenced by RotateInDegrees(), and cs349::scheme_turtle_rotate().
{
     instructions.push_back(new TurtleGraphicsRotateOp(theta));
     if (redrawNow) {
       this->GoToStep(this->GetNumSteps());
     }
   }
void cs349::TurtleGraphics::RotateInDegrees (double degrees, bool redrawNow = true)
Rotates the turtle by the amount specified, optionally redrawing it now or sometime in the future (the delay is useful if giving a bunch of commands at once).
Definition at line 60 of file TurtleGraphics.cpp.
References PI, and Rotate().
Referenced by cs349::TurtlePanel::PaintComponent().
{
     this->Rotate(degrees / 180.0 * PI, redrawNow);
   }
AffineTransform cs349::TurtleGraphics::WalkInstructions (Graphics * g, long stepNum, bool executeOps) const private
Definition at line 117 of file TurtleGraphics.cpp.
References cs349::Graphics::DrawLine(), cs349::TurtleGraphicsOp::ExecuteOp(), cs349::TurtleGraphicsOp::GetNewTransform(), cs349::TurtleGraphicsOp::GetNumSteps(), GetNumSteps(), GetRotation(), cs349::Graphics::GetTransform(), instructions, LOG_DEBUG, cs349::Graphics::SetTransform(), cs349::TurtleGraphicsOp::ToString(), TURTLE_LENGTH, cs349::Point::x, and cs349::Point::y.
Referenced by GetAffineTransform(), and PaintComponent().
{
     long curStep = 0;
     long numSteps = max(0L, min(this->GetNumSteps(), stepNum));
     AffineTransform originalTransform;
     AffineTransform curTransform;
     LOG_DEBUG << "Turtle WalkInstructions";
     LOG_DEBUG << "Step num requested: " << stepNum;
     LOG_DEBUG << "Num steps available: " << this->GetNumSteps();
     LOG_DEBUG << "Num steps to do: " << numSteps;
     if (executeOps) {
       originalTransform = g->GetTransform();
     }
     for (vector<TurtleGraphicsOp*>::const_iterator i = instructions.begin(); i != instructions.end(); i++) {
       if (curStep >= numSteps) {
         break;
       }
       TurtleGraphicsOp* op = *i;
       int numStepsLeft = numSteps - curStep;
       int numStepsForOp = 0;
       if (numStepsLeft > op->GetNumSteps()) {
         numStepsForOp = op->GetNumSteps();
       } else {
         numStepsForOp = numStepsLeft;
       }
       LOG_DEBUG << "Cur step num: " << curStep;
       LOG_DEBUG << "Num steps left: " << numStepsLeft;
       LOG_DEBUG << op->ToString();
       LOG_DEBUG << "Num steps for turtle op: " << numStepsForOp;
       if (executeOps) {
         op->ExecuteOp(g, numStepsForOp);
       }
       Point origin;
       Point curLocation = curTransform * origin;
       AffineTransform newTransform = op->GetNewTransform(numStepsForOp);
       curTransform = curTransform * newTransform;
       Point newLocation = curTransform * origin;
       double newTheta = GetRotation(curTransform);
       LOG_DEBUG << "Current turtle location: (" << curLocation.x << ", " << curLocation.y << ")";
       LOG_DEBUG << "New turtle location: (" << newLocation.x << ", " << newLocation.y << ")";
       LOG_DEBUG << "New rotation: " << newTheta;
       LOG_DEBUG << "";
       if (executeOps) {
         g->SetTransform(originalTransform * curTransform);
       }
       curStep += numStepsForOp;
     }
     if (executeOps) {
       // Draw the turtle
       g->DrawLine(Point(0, TURTLE_LENGTH/2), Point(0, -TURTLE_LENGTH/2));
       g->DrawLine(Point(0, -TURTLE_LENGTH/2), Point(TURTLE_LENGTH, 0));
       g->DrawLine(Point(TURTLE_LENGTH, 0), Point(0, TURTLE_LENGTH/2));
       g->SetTransform(originalTransform);
     }
     return curTransform;
   }
Member Data Documentation
long cs349::TurtleGraphics::drawStepNum private
Draw through step num drawStepNum
Definition at line 33 of file TurtleGraphics.h.
Referenced by GoToStep(), PaintComponent(), and TurtleGraphics().
vector<TurtleGraphicsOp*> cs349::TurtleGraphics::instructions private
Definition at line 32 of file TurtleGraphics.h.
Referenced by DeleteInstructions(), DrawPoint(), DrawText(), Forward(), GetInstructions(), GetNumSteps(), Rotate(), and WalkInstructions().
vector<ValueListener*> cs349::TurtleGraphics::listeners private
Definition at line 40 of file TurtleGraphics.h.
Referenced by AddValueListener(), NotifyListeners(), and RemoveValueListener().
const int cs349::TurtleGraphics::TURTLE_LENGTH = 10 static private
Definition at line 34 of file TurtleGraphics.h.
Referenced by WalkInstructions().
The documentation for this class was generated from the following files:
TurtleGraphics.h
TurtleGraphics.cpp