CS349 WatGUI: cs349::MainPanel Class Reference
cs349::MainPanel Class Reference
#include "MainPanel.h"
Public Member Functions
MainPanel ()
Public Member Functions inherited from cs349::Panel
Panel (const string &name)
Public Member Functions inherited from cs349::Component
Component (const string &name)
virtual ~Component ()
virtual string GetName () const
virtual void AddComponent (Component *child)
virtual void RemoveComponent (Component *child)
virtual unsigned long GetBackgroundColor () const
virtual Rectangle GetBounds () const
virtual unsigned long GetForegroundColor () const
virtual Component * GetParent ()
virtual XWindow * GetParentWindow ()
virtual bool HandleKeyEvent (const KeyEvent &e)
virtual bool HandleMouseEvent (const MouseEvent &e)
virtual bool IsPointInComponent (const Point &p) const
virtual bool IsVisible () const
virtual void Paint (Graphics *g)
virtual void Repaint ()
virtual void Repaint (const Rectangle &r)
virtual void SetBackgroundColor (unsigned long c)
virtual void SetForegroundColor (unsigned long c)
virtual void SetBounds (const Rectangle &r)
virtual void SetLocation (const Point &p)
virtual void SetDebugDelay (unsigned long delayMS)
virtual void SetParent (Component *parent)
virtual void SetSize (int width, int height)
virtual void SetVisible (bool visible)
long GetComponentNum () const
vector< Component * > GetDepthFirstInteractorTree () const
vector< Component * > GetBreadthFirstInteractorTree () const
Additional Inherited Members
Static Public Member Functions inherited from cs349::Component
static Component * GetComponent (long componentNum)
Protected Member Functions inherited from cs349::Panel
virtual void PaintComponent (Graphics *g)
Protected Attributes inherited from cs349::Component
vector< Component * > children
All the children of this Component.
Detailed Description
The MainPanel is simply the Component which will contain all other elements of your interface. In our unit tests, we will instantiate an instance of this object, then programmatically test your individual components.
We should be able to create an instance of this object, place it in an arbitrary window, and see the full interface specified for the assignment contained within this panel.
In the constructor, you should set the size of this panel to the desired size.
Definition at line 22 of file MainPanel.h.
Constructor & Destructor Documentation
MainPanel::MainPanel ()
Constructs the main panel for the application. All components should be added to this panel.
You should set the size of this panel in the constructor so that information can be used to size the XWindow to the appropriate size.
turtle->RotateInDegrees(45);
Definition at line 12 of file MainPanel.cpp.
References cs349::Component::AddComponent(), PLAYBACK_PANEL_ID, cs349::Component::SetBounds(), cs349::Component::SetVisible(), and TURTLE_GRAPHICS_PANEL_ID.
   : Panel(MAIN_PANEL_ID)
 {
   // TODO CS349: Create your entire interface here. You will need to
   // modify the provided code below to lay things out the way you like
   // Note the use of unique identifiers for each widget when they are
   // constructed. See A2WidgetIdentifiers.h and the assignment
   // specification for the identifiers you should use for each of the
   // components you create. These identifiers are used for unit tests
   // to easily identify components in the interactor tree.
   Component* turtleGraphicsPanel = new TurtlePanel(TURTLE_GRAPHICS_PANEL_ID);
   //TurtleGraphics* turtle = new TurtleGraphics(TURTLE_GRAPHICS_WIDGET_ID);
   this->SetBounds(Rectangle(0, 0, 500, 400));
   turtleGraphicsPanel->SetBounds(Rectangle(0, 0, 300, 330));
   //turtle->SetBounds(Rectangle(0, 30, 300, 300));
   //turtleGraphicsPanel->AddComponent(turtle);
   this->AddComponent(turtleGraphicsPanel);
   //turtle->SetVisible(true);
   turtleGraphicsPanel->SetVisible(true);
   // TODO CS349: Add other initialization code here
   // TODO CS349
   PlaybackPanel *pp = new PlaybackPanel(PLAYBACK_PANEL_ID);
     pp->SetBounds(Rectangle(350,0,500,200));
   this->AddComponent(pp);
   // Some simple operations to show the turtle when starting up
   // This is an entirely random set of instructions
   // Once started up, try typing this into the console:
   // (turtle-star (find-turtle-graphics-widget) 300 23)
   // The 300 argument is the length of the edges of the star, in
   // pixels
   // The 23 argument is the number of points for the star
   //turtle->Forward(100, true);
   //turtle->RotateInDegrees(135);
   //  turtle->Forward(65, true);
 //  turtle->RotateInDegrees(135);
 //  turtle->Forward(100, true);
 //  turtle->RotateInDegrees(150);
 //  turtle->Forward(30, true);
 }
The documentation for this class was generated from the following files:
MainPanel.h
MainPanel.cpp