CS349 WatGUI: cs349::Slider Class Reference
cs349::Slider Class Reference
#include "Slider.h"
Public Types
enum OrientationType { HORIZONTAL_SLIDER, VERTICAL_SLIDER }
Public Member Functions
Slider (const string &name, OrientationType orientation)
void AddValueListener (ValueListener *l)
void RemoveValueListener (ValueListener *l)
int GetMinimum () const
int GetMaximum () const
int GetCurValue () const
void SetMinimum (int minValue)
void SetMaximum (int maxValue)
void SetCurValue (int value)
OrientationType GetOrientation () const
void SetOrientation (OrientationType orientation)
string GetLowerBoundLabel () const
string GetUpperBoundLabel () const
string GetThumbLabel () const
void SetLowerBoundLabel (const string &label)
void SetUpperBoundLabel (const string &label)
void SetThumbLabel (const string &label)
Public Member Functions inherited from cs349::Component
Component (const string &name)
virtual ~Component ()
virtual string GetName () const
virtual void AddComponent (Component *child)
virtual void RemoveComponent (Component *child)
virtual unsigned long GetBackgroundColor () const
virtual Rectangle GetBounds () const
virtual unsigned long GetForegroundColor () const
virtual Component * GetParent ()
virtual XWindow * GetParentWindow ()
virtual bool HandleKeyEvent (const KeyEvent &e)
virtual bool HandleMouseEvent (const MouseEvent &e)
virtual bool IsPointInComponent (const Point &p) const
virtual bool IsVisible () const
virtual void Paint (Graphics *g)
virtual void Repaint ()
virtual void Repaint (const Rectangle &r)
virtual void SetBackgroundColor (unsigned long c)
virtual void SetForegroundColor (unsigned long c)
virtual void SetBounds (const Rectangle &r)
virtual void SetLocation (const Point &p)
virtual void SetDebugDelay (unsigned long delayMS)
virtual void SetParent (Component *parent)
virtual void SetSize (int width, int height)
virtual void SetVisible (bool visible)
long GetComponentNum () const
vector< Component * > GetDepthFirstInteractorTree () const
vector< Component * > GetBreadthFirstInteractorTree () const
Protected Member Functions
virtual void PaintComponent (Graphics *g)
Private Attributes
int lowerBound
int upperBound
int curValue
string lowerBoundLabel
string upperBoundLabel
string thumbLabel
OrientationType orientation
Additional Inherited Members
Static Public Member Functions inherited from cs349::Component
static Component * GetComponent (long componentNum)
Protected Attributes inherited from cs349::Component
vector< Component * > children
All the children of this Component.
Detailed Description
The Slider is a widget that allows the user to select a value from a bounded range. This particular Slider provides facilities to paint labels next to the ends of the scale, as well as next to the current value (above the thumb used to change the slider value).
Definition at line 20 of file Slider.h.
Member Enumeration Documentation
enum cs349::Slider::OrientationType
Orientation types for Slider components
Enumerator
HORIZONTAL_SLIDER
VERTICAL_SLIDER
Definition at line 25 of file Slider.h.
{
     HORIZONTAL_SLIDER,
     VERTICAL_SLIDER
   };
Constructor & Destructor Documentation
Slider::Slider (const string & name, OrientationType orientation)
Creates a new instance of a Slider with the name given. The name argument is used for unit tests when testing the interactor tree. Thus, the name should be unique.
Parameters
name A unique name used to identify this Slider. This name should not be printed out when painting
orientation Whether to make a horizontal or vertical slider
Definition at line 9 of file Slider.cpp.
References curValue, lowerBound, lowerBoundLabel, orientation, thumbLabel, upperBound, and upperBoundLabel.
   : Component(name)
 {
   lowerBound = 0;
   upperBound = 0;
   curValue = 0;
   lowerBoundLabel = "";
   upperBoundLabel = "";
   thumbLabel = "";
   this->orientation = orientation;
 // TODO CS349
 }
Member Function Documentation
void Slider::AddValueListener (ValueListener * l)
Adds a listener to this slider, which will be called when the slider value is changed. Slider is not responsible for the memory management of the ValueListener – external code is responsible for removing the listener and deleting it when it is no longer needed.
Definition at line 23 of file Slider.cpp.
Referenced by TEST().
{
 // TODO CS349
 }
int Slider::GetCurValue () const
Gets the current value of the slider.
Definition at line 39 of file Slider.cpp.
References curValue.
Referenced by TEST().
{
   return curValue;
 }
string Slider::GetLowerBoundLabel () const
Gets the label shown next to the lower bound of the slider
Definition at line 68 of file Slider.cpp.
References lowerBoundLabel.
{
   return lowerBoundLabel;
 }
int Slider::GetMaximum () const
Gets the maximum value supported by the slider.
Definition at line 35 of file Slider.cpp.
References upperBound.
Referenced by TEST().
{
   return upperBound;
 }
int Slider::GetMinimum () const
Gets the minimum value supported by the slider.
Definition at line 31 of file Slider.cpp.
References lowerBound.
Referenced by TEST().
{
   return lowerBound;
 }
Slider::OrientationType Slider::GetOrientation () const
Returns the orientation of the slider (whether it is horizontal or vertical).
Definition at line 55 of file Slider.cpp.
References orientation.
{
   return orientation;
 }
string Slider::GetThumbLabel () const
Gets the label shown next to the thumb of the slider (where the thumb is the part of the slider the user manipulates)
Definition at line 76 of file Slider.cpp.
References thumbLabel.
{
   return thumbLabel;
 }
string Slider::GetUpperBoundLabel () const
Gets the label shown next to the upper bound of the slider
Definition at line 72 of file Slider.cpp.
References upperBoundLabel.
{
   return upperBoundLabel;
 }
void Slider::PaintComponent (Graphics * g) protected virtual
The method that does the actual painting of the component once the Graphics context object has been set up by the Paint method in Component.
Implements cs349::Component.
Definition at line 64 of file Slider.cpp.
{
 // TODO CS349
 }
void Slider::RemoveValueListener (ValueListener * l)
Removes the specified ValueListener from the Slider.
Definition at line 27 of file Slider.cpp.
{
 // TODO CS349
 }
void Slider::SetCurValue (int value)
Sets the current value of the slider and calls all ValueListeners associated with the Slider. The Slider should repaint itself after a new value is set.
Definition at line 51 of file Slider.cpp.
Referenced by TEST().
{
 // TODO CS349
 }
void Slider::SetLowerBoundLabel (const string & label)
Sets the label shown next to the lower bound of the slider
Definition at line 80 of file Slider.cpp.
References lowerBoundLabel, and cs349::Component::Repaint().
{
   this->lowerBoundLabel = label;
   this->Repaint();
 }
void Slider::SetMaximum (int maxValue)
Sets the maximum value of the slider. If the Slider is visible, it should repaint itself to update the new bounds.
Definition at line 47 of file Slider.cpp.
Referenced by TEST().
{
 // TODO CS349
 }
void Slider::SetMinimum (int minValue)
Sets the minimum value of the slider. If the Slider is visible, it should repaint itself to update the new bounds.
Definition at line 43 of file Slider.cpp.
Referenced by TEST().
{
 // TODO CS349
 }
void Slider::SetOrientation (OrientationType orientation)
Sets the orientation of the slider to be horizontal or vertical.
Definition at line 59 of file Slider.cpp.
References orientation, and cs349::Component::Repaint().
{
   this->orientation = orientation;
   this->Repaint();
 }
void Slider::SetThumbLabel (const string & label)
Sets the label shown next to the thumb of the slider, where the thumb is the part that the user manipulates
Definition at line 90 of file Slider.cpp.
References cs349::Component::Repaint(), and thumbLabel.
{
   this->thumbLabel = label;
   this->Repaint();
 }
void Slider::SetUpperBoundLabel (const string & label)
Sets the label shown next to the upper bound of the slider
Definition at line 85 of file Slider.cpp.
References cs349::Component::Repaint(), and upperBoundLabel.
{
   this->upperBoundLabel = label;
   this->Repaint();
 }
Member Data Documentation
int cs349::Slider::curValue private
Definition at line 32 of file Slider.h.
Referenced by GetCurValue(), and Slider().
int cs349::Slider::lowerBound private
Definition at line 30 of file Slider.h.
Referenced by GetMinimum(), and Slider().
string cs349::Slider::lowerBoundLabel private
Definition at line 33 of file Slider.h.
Referenced by GetLowerBoundLabel(), SetLowerBoundLabel(), and Slider().
OrientationType cs349::Slider::orientation private
Definition at line 36 of file Slider.h.
Referenced by GetOrientation(), SetOrientation(), and Slider().
string cs349::Slider::thumbLabel private
Definition at line 35 of file Slider.h.
Referenced by GetThumbLabel(), SetThumbLabel(), and Slider().
int cs349::Slider::upperBound private
Definition at line 31 of file Slider.h.
Referenced by GetMaximum(), and Slider().
string cs349::Slider::upperBoundLabel private
Definition at line 34 of file Slider.h.
Referenced by GetUpperBoundLabel(), SetUpperBoundLabel(), and Slider().
The documentation for this class was generated from the following files:
Slider.h
Slider.cpp