CS349 WatGUI: cs349::XApplication Class Reference
cs349::XApplication Class Reference
#include "XApplication.h"
Public Member Functions
~XApplication ()
Display * GetXDisplay () const
int GetDefaultScreen () const
unsigned long GetBlackColor () const
unsigned long GetWhiteColor () const
EventQueue * GetEventQueue ()
void SetEventQueue (EventQueue *eventQueue)
void Run (bool runOnce=false)
void Quit ()
Static Public Member Functions
static XApplication * GetInstance ()
Private Member Functions
XApplication ()
int HandleXError (Display *display)
void CheckForXEvents ()
Private Attributes
Display * display
A pointer to the display.
int screen
Represents the default screen to display on.
bool quit
Whether the app should continue to run, or quit.
EventQueue * eventQueue
The event queue used to manage events.
Static Private Attributes
static XApplication * s_Instance = NULL
Friends
int ErrorHandler (Display *display)
Detailed Description
XApplication is the back-bone of your application. XApplication does the following:
Initializes and maintains the connection with X, and provides access to important X variables (such as the values for black and white colors).
Implements the event loop via its Run() method. In the event loop, new events are received from X, packaged up as our own custom Event objects, and added to the EventQueue object. Events are then peeled off the event queue in FIFO order, and asked to deliver themselves.
XApplication is a singleton: There is only one instance of it in existence throughout the lifetime of the application. As such, you don't directly instantiate the XApplication object. Instead, you call XApplication::GetInstance().
Definition at line 33 of file XApplication.h.
Constructor & Destructor Documentation
cs349::XApplication::XApplication () private
Private constructor so only one instance can be created (it's a singleton). Use GetInstance() to construct/get a pointer to the actual object.
Definition at line 30 of file XApplication.cpp.
References display, eventQueue, LOG_FATAL, quit, and screen.
Referenced by GetInstance().
   {
     eventQueue = new EventQueue();
     // Initialize the X display and get the default screen
     display = XOpenDisplay("");
     if (!display) {
       LOG_FATAL << "Error: Couldn't open X display";
       return;
     }
     screen = DefaultScreen(display);
     quit   = false;
   }
cs349::XApplication::~XApplication ()
When this destructor is called, the singleton (global) instance is set to NULL, allowing GetInstance() to be called again (and thus creating a new global XApplication object).
Definition at line 43 of file XApplication.cpp.
References display, eventQueue, cs349::XWindow::GetWindowList(), and s_Instance.
   {
     if (display != NULL) {
       vector<XWindow*> windows = XWindow::GetWindowList();
       for (vector<XWindow*>::iterator win = windows.begin(); win != windows.end(); win++) {
         delete (*win);
       }
       XCloseDisplay(display);
       display = NULL;
     }
     delete eventQueue;
     eventQueue = NULL;
     s_Instance = NULL;
   }
Member Function Documentation
void cs349::XApplication::CheckForXEvents () private
This method checks whether any X events are pending. If so, it packages them up as our own events and adds them to the eventQueue.
Definition at line 125 of file XApplication.cpp.
References cs349::EventQueue::AddEventToQueue(), display, eventQueue, cs349::XWindow::GetGraphics(), cs349::XWindow::GetXWindowForWindow(), cs349::KeyEvent::keyPress, cs349::KeyEvent::keyRelease, LOG_TODO, cs349::MouseEvent::mouseDown, cs349::MouseEvent::mouseDrag, cs349::MouseEvent::mouseMove, cs349::MouseEvent::mouseUp, and cs349::Graphics::SetClipRect().
Referenced by Run().
{
     /*
      * TODO for CS349 assignment:
      * Check if there is an X event pending. If so, package it up
      * using our own Event classes, and add it to the eventQueue.
      *
      * See the documentation at
      * http://tronche.com/gui/x/xlib/events/types.html to learn how to
      * identify the different types of X events. We have shown how to
      * get the Expose event (which indicates your window should
      * repaint itself) and package it up as a PaintEvent.
      *
      * Note that XEvent is a union of structs. This union is
      * documented on the page following the one above:
      * http://tronche.com/gui/x/xlib/events/structures.html
      *
      * If you are unfamiliar with C/C++ unions, or need a refresher,
      * see:
      * http://www.tutorialspoint.com/cprogramming/c_unions.htm
      * http://stackoverflow.com/questions/346536/difference-between-a-structure-and-a-union-in-c
      *
      * Another thing to note is that nothing will paint on your window
      * until it is mapped on the screen. You don't necessarily need to
      * be aware of when it is mapped, just be aware that until it's
      * displayed, any painting operations will have no effect when
      * it's actually put on the screen.
      *
      * One thing you may be wondering is why we package up an event
      * and add it to the event queue, rather than dispatching it right
      * away. The reason is that events may be added to the queue by
      * other objects (such as TimerEvents). Thus, to preserve proper
      * temporal ordering of events, you need to add events to the
      * queue and dispath them one by one.
      */
       bool button_pressed = false;
     if (XPending(this->display)) {
       // Get event, package it up, add it to the queue
       Event* newEvent = NULL;
       XEvent event;
       XNextEvent(this->display, &event);
       XWindow* window = XWindow::GetXWindowForWindow(event.xany.window);
         KeySym key;
         char key2;
         int count;
         char buffer[500];
       LOG_TODO << "TODO CS349: Implement XApplication::CheckForXEvents (remove when implemented)";
       switch (event.type) {
       case Expose:
         newEvent = new PaintEvent(window, Rectangle(event.xexpose.x, event.xexpose.y, event.xexpose.width, event.xexpose.height));
         break;
 // TODO CS349
           case ConfigureNotify:
               window->GetGraphics()->SetClipRect(Rectangle(0, 0, event.xconfigure.width, event.xconfigure.height));
               newEvent = new PaintEvent(window, Rectangle(0, 0, event.xconfigure.width, event.xconfigure.height));
               break;
           case KeyPress://handle key press event
               count = XLookupString((XKeyEvent*)&event, buffer, 500, &key, NULL);
               key2 = (char)key;
               newEvent = new KeyEvent(window,KeyEvent::keyPress,key2);
               break;
           case KeyRelease:
               count = XLookupString((XKeyEvent*)&event, buffer, 500, &key, NULL);
               key2 = (char)key;
               newEvent = new KeyEvent(window,KeyEvent::keyRelease,key2);
               break;
           case ButtonPress:
               newEvent = new MouseEvent(window,MouseEvent::mouseDown,Point(event.xbutton.x, event.xbutton.y));
               button_pressed = true;
               break;
           case ButtonRelease:
               newEvent = new MouseEvent(window,MouseEvent::mouseUp,Point(event.xbutton.x, event.xbutton.y));
               button_pressed = false;
               break;
           case MotionNotify:
               if(button_pressed){
                   newEvent = new MouseEvent(window,MouseEvent::mouseDrag,Point(event.xmotion.x, event.xmotion.y));
               }
               else{
                   newEvent = new MouseEvent(window,MouseEvent::mouseMove,Point(event.xmotion.x, event.xmotion.y));
               }
               break;
       case DestroyNotify:
         // You can ignore this
         LOG(INFO) << "Destroy notify event received";
         break;
       }
       if (newEvent != NULL) {
         eventQueue->AddEventToQueue(newEvent);
       }
     }
   }
unsigned long cs349::XApplication::GetBlackColor () const
Gets the value representing black from this X server.
Definition at line 67 of file XApplication.cpp.
References display, and screen.
Referenced by cs349::Component::Component(), cs349::Graphics::DebugDelay(), and cs349::XWindow::XWindow().
   {
     return BlackPixel(this->display, this->screen);
   }
int cs349::XApplication::GetDefaultScreen () const
Retrieves the default screen for this X server.
Definition at line 72 of file XApplication.cpp.
References screen.
   {
     return this->screen;
   }
EventQueue * cs349::XApplication::GetEventQueue ()
Returns a pointer to this app's EventQueue object, to be able to add Events to it.
Definition at line 77 of file XApplication.cpp.
References eventQueue.
Referenced by FlushEventQueue(), main(), cs349::XWindow::Repaint(), cs349::scheme_simulate_key_event(), cs349::scheme_simulate_mouse_event(), cs349::scheme_simulate_paint_event(), SimulateClick(), SimulateDrag(), and TEST().
   {
     return eventQueue;
   }
XApplication * cs349::XApplication::GetInstance () static
Gets a pointer to the XApplication object (constructing it, if necessary).
Definition at line 58 of file XApplication.cpp.
References s_Instance, and XApplication().
Referenced by cs349::Component::Component(), cs349::Graphics::DebugDelay(), cs349::ErrorHandler(), cs349::Graphics::Graphics(), cs349::TurtlePanel::PaintComponent(), cs349::PlaybackPanel::PaintComponent(), cs349::XWindow::Repaint(), cs349::scheme_call_c_function(), cs349::scheme_simulate_key_event(), cs349::scheme_simulate_mouse_event(), cs349::scheme_simulate_paint_event(), TEST(), and cs349::XWindow::XWindow().
   {
     if (!XApplication::s_Instance) {
       s_Instance = new XApplication();
     }
     return s_Instance;
   }
unsigned long cs349::XApplication::GetWhiteColor () const
Gets the value representing white from this X server.
Definition at line 92 of file XApplication.cpp.
References display, and screen.
Referenced by cs349::Component::Component(), cs349::Graphics::DebugDelay(), and cs349::XWindow::XWindow().
   {
     return WhitePixel(this->display, this->screen);
   }
Display * cs349::XApplication::GetXDisplay () const
Retrieves the X Display for this X server.
Definition at line 97 of file XApplication.cpp.
References display.
Referenced by cs349::XWindow::XWindow().
   {
     return this->display;
   }
int cs349::XApplication::HandleXError (Display * display) private
Definition at line 102 of file XApplication.cpp.
References scheme_interpreter_shutdown().
Referenced by cs349::ErrorHandler().
   {
     /*
       This method is called whenever there is a serious X error. This
       method will be called when the user manually closes the window.
       You could clean up the event queue, release memory, and anything
       else needed before the application quits, because once this
       method returns, X will forcibly terminate the entire
       application.
     */
     // Shut down the Scheme interpreter so it cleanly exits readline.
     // Otherwise, it puts the terminal in a funky state
     scheme_interpreter_shutdown();
     return -1;
   }
void cs349::XApplication::Quit ()
Stops the event loop.
Definition at line 119 of file XApplication.cpp.
References quit.
Referenced by Run().
   {
     quit = true;
   }
void cs349::XApplication::Run (bool runOnce = false)
Starts the application event loop. This will run until "Quit" is called, the user closes the window, or will only run once if the runOnce flag is set to true. For normal operation, runOnce should be set to false, indicating the application should run until the user signals they wish to quit. However, for unit testing, runOnce can be set to true, allowing unit tests to test single runs through the event loop.
If Quit is called, and then Run is called again, Run will reset the quit flag to run again until Quit is called.
Parameters
runOnce A flag to indicate whether the event loop should run continuously just once. If runOnce=false, the event loop will run until a) Quit is called or b) the user closes the window. If runOnce=true, it will run just a single pass through the event loop
Definition at line 222 of file XApplication.cpp.
References CheckForXEvents(), display, ErrorHandler, eventQueue, LOG_TODO, cs349::EventQueue::ProcessNextEvent(), quit, Quit(), and scheme_interpreter_service().
Referenced by FlushEventQueue(), main(), and TEST().
   {
     XSetIOErrorHandler(ErrorHandler);
     /*
      * This is where you will implement the event loop. The basic
      * logic of the event loop is as follows:
      * - You should service the CS349 Scheme interpreter to ensure it
      *   progresses (executes any scripts, accepts any user keyboard
      *   input) (already done for you)
      * - Check the return code for scheme_interpreter_service. If it
      *   returns a non-zero value, the application should quit
      * - You need to determine whether there are any events pending in
      *   X lib: call CheckForXEvents().
      * - You should call EventQueue's ProcessNextEvent() method to
      *   process events and service the timers. Note, you should call
      *   this *even if there are no events pending*, since it will
      *   service the timers.
      * - You can optionally call XFlush() to flush X's queue of
      *   graphics commands to the X server, but it is likely
      *   unnecessary given calls to other Xlib functions. See the
      *   following for more information:
      *   http://tronche.com/gui/x/xlib/event-handling/XFlush.html
      * - You should sleep if there is nothing left to do (i.e., there
      *   are no events in our event queue or pending in X's event
      *   queue -- check with XPending). Sleeping for a bit will ensure
      *   the CPU is not throttled.
      * - If you sleep, sleep for a very small amount of time, say
      *   1/1000 of a second, to enable interactive typing rates on the
      *   console. (See the usleep function for fine-grained sleep
      *   amounts).
      * - We *will* check to ensure your app doesn't throttle the CPU
      *   when idle, so make sure you sleep when there are no events.
      */
     this->quit = false;
     do {
       int interpreterReturnCode = 0;
       interpreterReturnCode = scheme_interpreter_service();
       if (interpreterReturnCode == 1) {
         this->Quit();
       }
       LOG_TODO << "TODO CS349: Implement event loop in XApplication::Run (remove when implemented)";
 // TODO CS349
         CheckForXEvents();
         eventQueue->ProcessNextEvent();
         XFlush(display);
         usleep(10000);
     } while (!this->quit && !runOnce);
   }
void cs349::XApplication::SetEventQueue (EventQueue * eventQueue)
Replaces the current event queue with the given event queue. When setting the event queue, XApplication takes over management of the memory represented by the passed in pointer. It will also delete the existing event queue, making any existing pointers to it invalid. Any events on the existing event queue will be thrown away when it is deleted.
This functionality is provided to make it easier to test event queue event handling in unit tests. You do not need to replace the event queue for normal operation of the toolkit.
Parameters
eventQueue A pointer to a heap-allocated EventQueue (it is a fatal error to pass in a NULL pointer)
Definition at line 82 of file XApplication.cpp.
References eventQueue, and LOG_FATAL.
   {
     if (!eventQueue) {
       LOG_FATAL << "Error: Cannot pass in NULL eventQueue to XApplication::SetEventQueue";
       return;
     }
     delete this->eventQueue;
     this->eventQueue = eventQueue;
   }
Friends And Related Function Documentation
int ErrorHandler (Display * display) friend
This is a callback from X whenever it encounters a serious error (such as when the user closes the window). You can ignore it
Referenced by Run().
Member Data Documentation
Display* cs349::XApplication::display private
A pointer to the display.
Definition at line 38 of file XApplication.h.
Referenced by CheckForXEvents(), GetBlackColor(), GetWhiteColor(), GetXDisplay(), Run(), XApplication(), and ~XApplication().
EventQueue* cs349::XApplication::eventQueue private
The event queue used to manage events.
Definition at line 41 of file XApplication.h.
Referenced by CheckForXEvents(), GetEventQueue(), Run(), SetEventQueue(), XApplication(), and ~XApplication().
bool cs349::XApplication::quit private
Whether the app should continue to run, or quit.
Definition at line 40 of file XApplication.h.
Referenced by Quit(), Run(), and XApplication().
XApplication * cs349::XApplication::s_Instance = NULL static private
Definition at line 36 of file XApplication.h.
Referenced by GetInstance(), and ~XApplication().
int cs349::XApplication::screen private
Represents the default screen to display on.
Definition at line 39 of file XApplication.h.
Referenced by GetBlackColor(), GetDefaultScreen(), GetWhiteColor(), and XApplication().
The documentation for this class was generated from the following files:
XApplication.h
XApplication.cpp