CS349 WatGUI: cs349::TurtleGraphicsOp Class Reference
cs349::TurtleGraphicsOp Class Reference abstract
#include "TurtleGraphicsOp.h"
Public Member Functions
virtual ~TurtleGraphicsOp ()
virtual long GetNumSteps () const =0
virtual AffineTransform GetNewTransform (long stepNum) const =0
virtual void ExecuteOp (Graphics *g, long stepNum) const =0
virtual string ToString () const =0
virtual string AsSexp () const =0
Detailed Description
Definition at line 10 of file TurtleGraphicsOp.h.
Constructor & Destructor Documentation
virtual cs349::TurtleGraphicsOp::~TurtleGraphicsOp () inline virtual
Definition at line 12 of file TurtleGraphicsOp.h.
 {}
Member Function Documentation
virtual string cs349::TurtleGraphicsOp::AsSexp () const pure virtual
Implemented in cs349::TurtleGraphicsDrawPointOp, cs349::TurtleGraphicsDrawTextOp, cs349::TurtleGraphicsRotateOp, and cs349::TurtleGraphicsForwardOp.
virtual void cs349::TurtleGraphicsOp::ExecuteOp (Graphics * g, long stepNum) const pure virtual
Implemented in cs349::TurtleGraphicsDrawPointOp, cs349::TurtleGraphicsDrawTextOp, cs349::TurtleGraphicsRotateOp, and cs349::TurtleGraphicsForwardOp.
Referenced by cs349::TurtleGraphics::WalkInstructions().
virtual AffineTransform cs349::TurtleGraphicsOp::GetNewTransform (long stepNum) const pure virtual
Implemented in cs349::TurtleGraphicsDrawPointOp, cs349::TurtleGraphicsDrawTextOp, cs349::TurtleGraphicsRotateOp, and cs349::TurtleGraphicsForwardOp.
Referenced by cs349::TurtleGraphics::WalkInstructions().
virtual long cs349::TurtleGraphicsOp::GetNumSteps () const pure virtual
Implemented in cs349::TurtleGraphicsDrawPointOp, cs349::TurtleGraphicsDrawTextOp, cs349::TurtleGraphicsRotateOp, and cs349::TurtleGraphicsForwardOp.
Referenced by cs349::TurtleGraphics::WalkInstructions().
virtual string cs349::TurtleGraphicsOp::ToString () const pure virtual
Implemented in cs349::TurtleGraphicsDrawPointOp, cs349::TurtleGraphicsDrawTextOp, cs349::TurtleGraphicsRotateOp, and cs349::TurtleGraphicsForwardOp.
Referenced by cs349::TurtleGraphics::WalkInstructions().
The documentation for this class was generated from the following file:
TurtleGraphicsOp.h