CS349 WatGUI: cs349::Graphics Class Reference
cs349::Graphics Class Reference
#include "Graphics.h"
Public Member Functions
virtual ~Graphics ()
void DrawLine (const Point &p1, const Point &p2)
void DrawLineSegments (const vector< vector< Point > > &lines)
void DrawPoint (const Point &p)
void DrawPoints (const vector< Point > &points)
void DrawPolygon (const vector< Point > &vertices)
void DrawRect (const Rectangle &r)
void DrawText (const Point &p, const string &text)
void FillPolygon (const vector< Point > &vertices)
void FillRect (const Rectangle &r)
GC GetGC ()
unsigned long GetBackgroundColor () const
virtual unsigned long GetDebugDelay () const
virtual void SetDebugDelay (unsigned long delayMS)
unsigned long GetForegroundColor () const
void SetBackgroundColor (unsigned long color)
void SetForegroundColor (unsigned long color)
int GetDrawingMode () const
void SetDrawingMode (int drawingMode)
Rectangle GetClipRect ()
void SetClipRect (const Rectangle &r)
AffineTransform GetTransform () const
void SetTransform (const AffineTransform &t)
Protected Member Functions
virtual void DebugDelay (const string &opName) const
Private Member Functions
Graphics (Display *display, Window window)
void PrepareGraphicsContext ()
XPoint * GetTransformedXPoints (const vector< Point > &points)
Private Attributes
Display * display
Window window
GC gc
X window Graphics Context.
Rectangle clipRect
AffineTransform transform
unsigned long backgroundColor
Background color to use.
unsigned long foregroundColor
Foreground color to use.
int drawingMode
Drawing mode.
unsigned long debugDelayMS
Delay to add to support debugging.
Friends
class XWindow
Detailed Description
This class encapsulates X lib's Graphics Context (GC) and provides the means by which components draw themselves on windows.
You can add functionality to this class (for example, there are no methods provided to draw arcs, ellipses, or circles).
You may want to add functionality to change fonts and determine the bounds of a string when drawn to the screen
Definition at line 34 of file Graphics.h.
Constructor & Destructor Documentation
cs349::Graphics::Graphics (Display * display, Window window) private
Private constructor. Called by XWindow class when a new window is created.
Definition at line 13 of file Graphics.cpp.
References clipRect, debugDelayMS, display, drawingMode, gc, cs349::XApplication::GetInstance(), cs349::Rectangle::height, SetBackgroundColor(), cs349::Rectangle::width, window, cs349::Rectangle::x, and cs349::Rectangle::y.
   {
     this->debugDelayMS = 0;
     this->display      = display;
     this->window       = window;
     this->gc           = XCreateGC(display, window, 0, 0);
     this->drawingMode  = GXcopy;
     // Set clip to current size of window
     XWindowAttributes attr;
     XGetWindowAttributes(this->display, this->window, &attr);
     this->clipRect.x = 0;
     this->clipRect.y = 0;
     this->clipRect.width = attr.width;
     this->clipRect.height = attr.height;
     // Initialize to sane defaults, even though these values will
     // typically be overwritten by Component when it paints itself
     this->SetBackgroundColor(XApplication::GetInstance()->GetBlackColor());
     this->SetBackgroundColor(XApplication::GetInstance()->GetWhiteColor());
   }
cs349::Graphics::~Graphics () virtual
Definition at line 35 of file Graphics.cpp.
References display, and gc.
   {
     XFreeGC(this->display, this->gc);
   }
Member Function Documentation
void cs349::Graphics::DebugDelay (const string & opName) const protected virtual
Definition at line 40 of file Graphics.cpp.
References debugDelayMS, cs349::XApplication::GetBlackColor(), GetForegroundColor(), cs349::XApplication::GetInstance(), cs349::XApplication::GetWhiteColor(), LOG_PAINT, and transform.
Referenced by DrawLine(), DrawLineSegments(), DrawPoint(), DrawPoints(), DrawPolygon(), DrawRect(), DrawText(), FillPolygon(), and FillRect().
{
     Point origin = Point(0, 0);
     Point x_axis = Point(1, 0);
     Point y_axis = Point(0, 1);
     LOG_PAINT << "Graphics op: " << opName << " with color: " << this->GetForegroundColor() << " (white/black: " << XApplication::GetInstance()->GetWhiteColor() << "/" << XApplication::GetInstance()->GetBlackColor() << ")";
     LOG_PAINT << "Points through current transform: (0,0) -> : " << (this->transform * origin) << " (1,0) -> : " << (this->transform * x_axis) << " (0,1) -> : " << (this->transform * y_axis);
     if (debugDelayMS > 0) {
       XFlush(XApplication::GetInstance()->GetXDisplay());
       usleep(debugDelayMS * 1000);
     }
   }
void cs349::Graphics::DrawLine (const Point & p1, const Point & p2)
Draws a line between the two points given, after transforming them via this object's current AffineTransform. Draws using the current foreground color.
Definition at line 61 of file Graphics.cpp.
References DebugDelay(), display, gc, PrepareGraphicsContext(), transform, window, cs349::Point::x, and cs349::Point::y.
Referenced by cs349::TurtleGraphicsForwardOp::ExecuteOp(), cs349::PlaybackPanel::PaintComponent(), cs349::scheme_graphics_draw_line(), and cs349::TurtleGraphics::WalkInstructions().
   {
     this->PrepareGraphicsContext();
     Point t1 = this->transform * p1;
     Point t2 = this->transform * p2;
     XDrawLine(this->display, this->window, this->gc, (int)t1.x, (int)t1.y, (int)t2.x, (int)t2.y);
     DebugDelay(string("DrawLine"));
   }
void cs349::Graphics::DrawLineSegments (const vector< vector< Point > > & lines)
Draws a series of line segments given by the vectors of Points, after transforming them via this object's current AffineTransform. Draws using the current foreground color.
Definition at line 70 of file Graphics.cpp.
References DebugDelay(), and DrawPolygon().
Referenced by cs349::scheme_graphics_draw_line_segments().
   {
     DebugDelay(string("DrawLineSegments (via call to DrawPolygon)"));
     for (vector<vector<Point> >::const_iterator iter=lines.begin(); iter != lines.end(); iter++) {
       this->DrawPolygon(*iter);
     }
   }
void cs349::Graphics::DrawPoint (const Point & p)
Draws a single point after transforming it via this object's current AffineTransform. Draws using the current foreground color.
Definition at line 78 of file Graphics.cpp.
References DebugDelay(), display, gc, PrepareGraphicsContext(), transform, window, cs349::Point::x, and cs349::Point::y.
Referenced by cs349::TurtleGraphicsDrawPointOp::ExecuteOp(), and cs349::scheme_graphics_draw_point().
   {
     this->PrepareGraphicsContext();
     Point newPoint = this->transform * p;
     XDrawPoint(this->display, this->window, this->gc, (int)newPoint.x, (int)newPoint.y);
     DebugDelay(string("DrawPoint"));
   }
void cs349::Graphics::DrawPoints (const vector< Point > & points)
Draws a series of points as given by the vector of Points, after transforming them via this object's current AffineTransform. Draws using the current foreground color.
Definition at line 86 of file Graphics.cpp.
References DebugDelay(), display, gc, GetTransformedXPoints(), PrepareGraphicsContext(), and window.
Referenced by cs349::scheme_graphics_draw_points().
   {
     this->PrepareGraphicsContext();
     XPoint* xPoints = this->GetTransformedXPoints(points);
     XDrawPoints(this->display, this->window, this->gc, xPoints, points.size(), CoordModeOrigin);
     delete[] xPoints;
     DebugDelay(string("DrawPoints"));
   }
void cs349::Graphics::DrawPolygon (const vector< Point > & vertices)
Draws the polygon specified by the vector of Points, after transforming them via this object's current AffineTransform. Draws using the current foreground color.
Definition at line 95 of file Graphics.cpp.
References DebugDelay(), display, gc, GetTransformedXPoints(), PrepareGraphicsContext(), and window.
Referenced by DrawLineSegments(), DrawRect(), and cs349::scheme_graphics_draw_polygon().
   {
     this->PrepareGraphicsContext();
     XPoint* xPoints = this->GetTransformedXPoints(vertices);
     XDrawLines(this->display, this->window, this->gc, xPoints, vertices.size(), CoordModeOrigin);
     delete[] xPoints;
     DebugDelay(string("DrawPolygon"));
   }
void cs349::Graphics::DrawRect (const Rectangle & r)
Draws the rectangle specified after transforming its points via this object's current AffineTransform. Draws using the current foreground color.
Definition at line 104 of file Graphics.cpp.
References DebugDelay(), DrawPolygon(), cs349::Rectangle::height, cs349::Rectangle::width, cs349::Rectangle::x, and cs349::Rectangle::y.
Referenced by cs349::TurtlePanel::PaintComponent(), and cs349::scheme_graphics_draw_rect().
   {
     Point p1 = Point(r.x, r.y);
     Point p2 = Point(r.x+r.width, r.y);
     Point p3 = Point(r.x+r.width, r.y+r.height);
     Point p4 = Point(r.x, r.y+r.height);
     vector<Point> points;
     points.push_back(p1);
     points.push_back(p2);
     points.push_back(p3);
     points.push_back(p4);
     points.push_back(p1);
     DebugDelay("DrawRect (via call to DrawPolygon)");
     this->DrawPolygon(points);
   }
void cs349::Graphics::DrawText (const Point & p, const string & text)
Draws the text given at the point specified, after transforming the point via this object's current AffineTransform. Draws using the current foreground color.
Definition at line 120 of file Graphics.cpp.
References DebugDelay(), display, gc, PrepareGraphicsContext(), transform, window, cs349::Point::x, and cs349::Point::y.
Referenced by cs349::TurtleGraphicsDrawTextOp::ExecuteOp(), cs349::TurtlePanel::PaintComponent(), cs349::PlaybackPanel::PaintComponent(), Clock::PaintComponent(), and cs349::scheme_graphics_draw_text().
   {
     this->PrepareGraphicsContext();
     XTextItem xTextItem;
     xTextItem.chars  = const_cast<char*>(text.c_str());
     xTextItem.nchars = text.size();
     xTextItem.font   = None;
     xTextItem.delta  = 0;
     Point newPoint = this->transform * p;
     XDrawText(this->display, this->window, this->gc, (int)newPoint.x, (int)newPoint.y, &xTextItem, 1);
     DebugDelay(string("DrawText"));
   }
void cs349::Graphics::FillPolygon (const vector< Point > & vertices)
Fills the polygon specified by the vector of Points, after transforming them via this object's current AffineTransform. Fills using the current foreground color.
Definition at line 133 of file Graphics.cpp.
References DebugDelay(), display, gc, GetTransformedXPoints(), PrepareGraphicsContext(), and window.
Referenced by FillRect(), and cs349::scheme_graphics_fill_polygon().
   {
     this->PrepareGraphicsContext();
     XPoint* xPoints = this->GetTransformedXPoints(vertices);
     XFillPolygon(this->display, this->window, this->gc, xPoints, vertices.size(), Complex, CoordModeOrigin);
     delete[] xPoints;
     DebugDelay(string("FillPolygon"));
   }
void cs349::Graphics::FillRect (const Rectangle & r)
Fills the rectangle specified, after transforming its points via this object's current AffineTransform. Fills using the current foreground color.
Definition at line 142 of file Graphics.cpp.
References DebugDelay(), FillPolygon(), cs349::Rectangle::height, cs349::Rectangle::width, cs349::Rectangle::x, and cs349::Rectangle::y.
Referenced by cs349::scheme_graphics_fill_rect().
   {
     Point p1 = Point(r.x, r.y);
     Point p2 = Point(r.x+r.width, r.y);
     Point p3 = Point(r.x+r.width, r.y+r.height);
     Point p4 = Point(r.x, r.y+r.height);
     vector<Point> points;
     points.push_back(p1);
     points.push_back(p2);
     points.push_back(p3);
     points.push_back(p4);
     points.push_back(p1);
     DebugDelay("FillRect (via call to FillPolygon)");
     this->FillPolygon(points);
   }
unsigned long cs349::Graphics::GetBackgroundColor () const
Returns the current background color set for this graphics context. Note that you currently have little use for this variable. See SetBackgroundColor for more information.
Definition at line 158 of file Graphics.cpp.
References backgroundColor.
Referenced by cs349::marshall_graphics_call().
   {
     return this->backgroundColor;
   }
Rectangle cs349::Graphics::GetClipRect ()
Gets the Graphics context's clip rect, with coordinates relative to the coordinate system specified by the current AffineTransform.
Definition at line 163 of file Graphics.cpp.
References clipRect, cs349::AffineTransform::GetInverse(), cs349::Rectangle::GetTopLeft(), transform, cs349::Point::x, and cs349::Point::y.
Referenced by cs349::marshall_graphics_call().
   {
     // Transform from window coordinates to current coordinates
     AffineTransform t = this->transform.GetInverse();
     Point p = t * this->clipRect.GetTopLeft();
     return Rectangle(p.x, p.y, this->clipRect.width, this->clipRect.height);
   }
unsigned long cs349::Graphics::GetDebugDelay () const virtual
Returns the delay, in milliseconds, being used when rendering graphics operations. Useful for debugging output.
Definition at line 53 of file Graphics.cpp.
References debugDelayMS.
Referenced by cs349::marshall_graphics_call().
{
     return debugDelayMS;
   }
int cs349::Graphics::GetDrawingMode () const
Gets the drawing mode (e.g., copy, xor, etc.). See X documentation for more info (http://tronche.com/gui/x/xlib/GC/manipulating.html).
Definition at line 176 of file Graphics.cpp.
References drawingMode.
   {
     return this->drawingMode;
   }
unsigned long cs349::Graphics::GetForegroundColor () const
The foreground color that will be used for drawing operations.
Definition at line 171 of file Graphics.cpp.
References foregroundColor.
Referenced by DebugDelay(), and cs349::marshall_graphics_call().
   {
     return this->foregroundColor;
   }
GC cs349::Graphics::GetGC ()
Returns
X lib's graphics context object.
Definition at line 181 of file Graphics.cpp.
References gc.
   {
     return this->gc;
   }
AffineTransform cs349::Graphics::GetTransform () const
AffineTransforms are used to alter how points, lines, rectangles, and polygons are drawn on the screen, by scaling, rotating, and translating them.
Returns
The current AffineTransform
Definition at line 186 of file Graphics.cpp.
References transform.
Referenced by cs349::TurtleGraphicsForwardOp::ExecuteOp(), cs349::marshall_graphics_call(), cs349::TurtlePanel::PaintComponent(), cs349::TurtleGraphics::PaintComponent(), and cs349::TurtleGraphics::WalkInstructions().
   {
     return this->transform;
   }
XPoint * cs349::Graphics::GetTransformedXPoints (const vector< Point > & points) private
Transforms the given points using this object's AffineTransform, returning a set of XPoint objects.
Definition at line 191 of file Graphics.cpp.
References transform, cs349::Point::x, and cs349::Point::y.
Referenced by DrawPoints(), DrawPolygon(), and FillPolygon().
   {
     XPoint* newPoints = new XPoint[points.size()];
     for (unsigned int i = 0; i < points.size(); i++) {
       Point p = this->transform * points[i];
       newPoints[i].x = (int)p.x;
       newPoints[i].y = (int)p.y;
     }
     return newPoints;
   }
void cs349::Graphics::PrepareGraphicsContext () private
Sets the graphic context using this object's attribute values.
Definition at line 202 of file Graphics.cpp.
References backgroundColor, clipRect, display, drawingMode, foregroundColor, gc, cs349::Rectangle::height, cs349::Rectangle::IsEmpty(), LOG_PAINT, cs349::Rectangle::width, cs349::Rectangle::x, and cs349::Rectangle::y.
Referenced by DrawLine(), DrawPoint(), DrawPoints(), DrawPolygon(), DrawText(), and FillPolygon().
   {
     XRectangle clip;
     XSetBackground(this->display, this->gc, this->backgroundColor);
     XSetForeground(this->display, this->gc, this->foregroundColor);
     XSetFunction(this->display, this->gc, this->drawingMode);
     clip.x = (int)this->clipRect.x;
     clip.y = (int)this->clipRect.y;
     clip.width = (int)this->clipRect.width;
     clip.height = (int)this->clipRect.height;
     XSetClipRectangles(this->display, this->gc, 0, 0, &clip, 1, Unsorted);
     if (this->clipRect.IsEmpty()) {
       LOG_PAINT << "Graphics: Clip rect is empty in PrepareGraphicsContext()";
     }
   }
void cs349::Graphics::SetBackgroundColor (unsigned long color)
Sets the graphics context's background color. Important: Setting this will have absolutely no visible effect on your window. This color is used when calling XClearArea in Xlib, but we currently do not provide a wrapper method for that function call. Instead, to clear the window to your desired background color, set the foreground color to the desired background color, then use FillRect.
Definition at line 219 of file Graphics.cpp.
References backgroundColor.
Referenced by Graphics(), and cs349::scheme_graphics_set_background_color().
   {
     this->backgroundColor = color;
   }
void cs349::Graphics::SetClipRect (const Rectangle & r)
Sets the Graphics context's clip rect, with coordinates relative to the coordinate system specified by the current AffineTransform.
Definition at line 224 of file Graphics.cpp.
References clipRect, cs349::Rectangle::GetTopLeft(), cs349::Rectangle::height, transform, cs349::Rectangle::width, cs349::Point::x, and cs349::Point::y.
Referenced by cs349::XApplication::CheckForXEvents(), cs349::XWindow::HandlePaintEvent(), and cs349::scheme_graphics_set_clip_rect().
   {
     // Transform into window coordinates
     Point p = this->transform * r.GetTopLeft();
     this->clipRect = Rectangle(p.x, p.y, r.width, r.height);
   }
void cs349::Graphics::SetDebugDelay (unsigned long delayMS) virtual
Sets the delay, in milliseconds, to add between performing graphics operations. Should only be used for debugging purposes.
Parameters
delayMS The delay, in milliseconds
Definition at line 57 of file Graphics.cpp.
References debugDelayMS.
Referenced by cs349::marshall_graphics_call().
{
     debugDelayMS = delayMS;
   }
void cs349::Graphics::SetDrawingMode (int drawingMode)
Sets the drawing mode (e.g., copy, xor, etc.). See X documentation for more info (http://tronche.com/gui/x/xlib/GC/manipulating.html).
Definition at line 236 of file Graphics.cpp.
References drawingMode.
   {
     this->drawingMode = drawingMode;
   }
void cs349::Graphics::SetForegroundColor (unsigned long color)
Sets the foreground color that will be used for drawing operations. Get valid color values from the Application object.
Definition at line 231 of file Graphics.cpp.
References foregroundColor.
Referenced by cs349::PlaybackPanel::PaintComponent(), cs349::TurtlePanel::PaintComponent(), and cs349::scheme_graphics_set_foreground_color().
   {
     this->foregroundColor = color;
   }
void cs349::Graphics::SetTransform (const AffineTransform & t)
AffineTransforms are used to alter how points, lines, rectangles, and polygons are drawn on the screen, by scaling, rotating, and translating them.
Use this to set the AffineTransform to use for any subsequent drawing/painting operations.
Definition at line 241 of file Graphics.cpp.
References transform.
Referenced by cs349::XWindow::HandlePaintEvent(), cs349::TurtlePanel::PaintComponent(), cs349::PlaybackPanel::PaintComponent(), cs349::TurtleGraphics::PaintComponent(), cs349::scheme_graphics_set_transform(), and cs349::TurtleGraphics::WalkInstructions().
   {
     this->transform = t;
   }
Friends And Related Function Documentation
friend class XWindow friend
Definition at line 56 of file Graphics.h.
Member Data Documentation
unsigned long cs349::Graphics::backgroundColor private
Background color to use.
Definition at line 50 of file Graphics.h.
Referenced by GetBackgroundColor(), PrepareGraphicsContext(), and SetBackgroundColor().
Rectangle cs349::Graphics::clipRect private
Important: Always stored in window* coordinates. This requires care in setting/getting
Definition at line 42 of file Graphics.h.
Referenced by GetClipRect(), Graphics(), PrepareGraphicsContext(), and SetClipRect().
unsigned long cs349::Graphics::debugDelayMS private
Delay to add to support debugging.
Definition at line 54 of file Graphics.h.
Referenced by DebugDelay(), GetDebugDelay(), Graphics(), and SetDebugDelay().
Display* cs349::Graphics::display private
X window display associated with this Graphics Context
Definition at line 37 of file Graphics.h.
Referenced by DrawLine(), DrawPoint(), DrawPoints(), DrawPolygon(), DrawText(), FillPolygon(), Graphics(), PrepareGraphicsContext(), and ~Graphics().
int cs349::Graphics::drawingMode private
Drawing mode.
Definition at line 52 of file Graphics.h.
Referenced by GetDrawingMode(), Graphics(), PrepareGraphicsContext(), and SetDrawingMode().
unsigned long cs349::Graphics::foregroundColor private
Foreground color to use.
Definition at line 51 of file Graphics.h.
Referenced by GetForegroundColor(), PrepareGraphicsContext(), and SetForegroundColor().
GC cs349::Graphics::gc private
X window Graphics Context.
Definition at line 41 of file Graphics.h.
Referenced by DrawLine(), DrawPoint(), DrawPoints(), DrawPolygon(), DrawText(), FillPolygon(), GetGC(), Graphics(), PrepareGraphicsContext(), and ~Graphics().
AffineTransform cs349::Graphics::transform private
The transform applied to drawing operations' coordinates before doing any actual drawing or painting.
Definition at line 46 of file Graphics.h.
Referenced by DebugDelay(), DrawLine(), DrawPoint(), DrawText(), GetClipRect(), GetTransform(), GetTransformedXPoints(), SetClipRect(), and SetTransform().
Window cs349::Graphics::window private
The X window associated with this Graphics Context
Definition at line 39 of file Graphics.h.
Referenced by DrawLine(), DrawPoint(), DrawPoints(), DrawPolygon(), DrawText(), FillPolygon(), and Graphics().
The documentation for this class was generated from the following files:
Graphics.h
Graphics.cpp